esphome:
  name: otgateway
  friendly_name: OpenTherm Gateway

  on_boot:
    priority: -100
    then:
      - lambda: |-
          // Link Equitherm number handles (for Equitherm::calculate_target_temp)
          opentherm::Equitherm::eq_n         = (esphome::number::Number *)&id(eq_n);
          opentherm::Equitherm::eq_k         = (esphome::number::Number *)&id(eq_k);
          opentherm::Equitherm::eq_t         = (esphome::number::Number *)&id(eq_t);
          opentherm::Equitherm::eq_fb_gain   = (esphome::number::Number *)&id(eq_fb_gain);

          // DHW
          opentherm::DHW::eco_temp_number = (esphome::number::Number *)&id(dhw_eco_temp);
          opentherm::DHW::normal_temp_number = (esphome::number::Number *)&id(dhw_normal_temp);

          // Diagnostics binary sensors
          using namespace opentherm::Diagnostics;
          ch_active_sensor   = (esphome::binary_sensor::BinarySensor *)&id(ch_active);
          dhw_active_sensor  = (esphome::binary_sensor::BinarySensor *)&id(dhw_active);
          dhw_flowing_sensor = (esphome::binary_sensor::BinarySensor *)&id(dhw_flowing);
          dhw_flow_rate_sensor = (esphome::sensor::Sensor *)&id(dhw_flow_rate);
          flame_sensor       = (esphome::binary_sensor::BinarySensor *)&id(boiler_flame);
          fault_sensor       = (esphome::binary_sensor::BinarySensor *)&id(boiler_fault);
          diagnostic_sensor  = (esphome::binary_sensor::BinarySensor *)&id(boiler_diag);
          comms_ok_sensor    = (esphome::binary_sensor::BinarySensor *)&id(comms_ok);
          fault_text_sensor  = (esphome::text_sensor::TextSensor *)&id(fault_text);


esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  port: !secret api_port
  encryption: 
    key: !secret api_encryption_key

ota:
  platform: esphome

wifi:
  reboot_timeout: 5min
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Opentherm Gateway"
    password: "Opentherm12345"

captive_portal:

external_components:
  - source: ./custom_components/opentherm

opentherm:
  id: otgw
  in_pin:         !secret in_pin 
  out_pin:        !secret out_pin 
  poll_interval:  !secret poll_interval
  rx_timeout:     !secret rx_timeout
  debug:          true

  boiler_temp:
    id: boiler_temp
    name: "Boiler Water Temperature"
  return_temp:
    id: return_temp
    name: "Return Temperature"
  modulation:
    id: modulation
    name: "Boiler Modulation"
  setpoint:
    id: setpoint
    name: "Control Setpoint"

binary_sensor:  !include data/binary_sensor.yaml
climate:        !include data/climate.yaml
number:         !include data/number.yaml
select:         !include data/select.yaml
sensor:         !include data/sensors.yaml
switch:         !include data/switch.yaml
text_sensor:    !include data/text_sensor.yaml
