esphome:
  name: otgateway
  friendly_name: OpenTherm Gateway

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  password: !secret api_password

ota:
  platform: esphome

wifi:
  reboot_timeout: 5min
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Opentherm Gateway"
    password: "Opentherm12345"

captive_portal:

external_components:
  - source: ./custom_components/opentherm

opentherm:
  id: otgw
  in_pin:         !secret in_pin 
  out_pin:        !secret out_pin 
  poll_interval:  !secret poll_interval
  rx_timeout:     !secret rx_timeout
  debug:          true

  boiler_temp:
    id: boiler_temp
    name: "Boiler Water Temperature"
  return_temp:
    id: return_temp
    name: "Return Temperature"
  modulation:
    id: modulation
    name: "Boiler Modulation"
  setpoint:
    id: setpoint
    name: "Control Setpoint"


climate:  !include data/climate.yaml
number:   !include data/number.yaml
sensor:   !include data/sensors.yaml

substitutions:
  eq_n: !secret eq_n
  eq_k: !secret eq_k
  eq_t: !secret eq_t
