esphome:
  name: otgateway
  friendly_name: OpenTherm Gateway

  on_boot:
    priority: -100
    then:
      - lambda: |-
          // DHW
          opentherm::DHW::eco_temp_number = (esphome::number::Number *)&id(dhw_eco_temp);
          opentherm::DHW::normal_temp_number = (esphome::number::Number *)&id(dhw_normal_temp);

          // Diagnostics binary sensors
          opentherm::Diagnostics::comms_ok_sensor = (esphome::binary_sensor::BinarySensor *)&id(ot_comms_ok);
          opentherm::Diagnostics::ch_active_sensor = (esphome::binary_sensor::BinarySensor *)&id(ch_active);
          opentherm::Diagnostics::dhw_active_sensor = (esphome::binary_sensor::BinarySensor *)&id(dhw_active);
          opentherm::Diagnostics::flame_sensor = (esphome::binary_sensor::BinarySensor *)&id(flame_on);
          opentherm::Diagnostics::fault_sensor = (esphome::binary_sensor::BinarySensor *)&id(boiler_fault);
          opentherm::Diagnostics::diagnostic_sensor = (esphome::binary_sensor::BinarySensor *)&id(boiler_diag);
          opentherm::Diagnostics::fault_text_sensor = (esphome::text_sensor::TextSensor *)&id(boiler_fault_message);



esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  password: !secret api_password

ota:
  platform: esphome

wifi:
  reboot_timeout: 5min
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Opentherm Gateway"
    password: "Opentherm12345"

captive_portal:

external_components:
  - source: ./custom_components/opentherm

opentherm:
  id: otgw
  in_pin:         !secret in_pin 
  out_pin:        !secret out_pin 
  poll_interval:  !secret poll_interval
  rx_timeout:     !secret rx_timeout
  debug:          true

  boiler_temp:
    id: boiler_temp
    name: "Boiler Water Temperature"
  return_temp:
    id: return_temp
    name: "Return Temperature"
  modulation:
    id: modulation
    name: "Boiler Modulation"
  setpoint:
    id: setpoint
    name: "Control Setpoint"

binary_sensor:  !include data/binary_sensor.yaml
climate:        !include data/climate.yaml
number:         !include data/number.yaml
select:         !include data/select.yaml
sensor:         !include data/sensors.yaml

text_sensor:
  - platform: template
    name: "Boiler Fault Message"
    id: boiler_fault_message
