esphome:
  name: otgateway
  friendly_name: OpenTherm Gateway

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome

external_components:
  - source: ./custom_components/opentherm

opentherm:
  id: otgw
  in_pin: GPIO5
  out_pin: GPIO6
  poll_interval: 10s

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Opentherm Gateway"
    password: "yAyQs84CkJpv"

captive_portal:
    